#make command to docker compose up the docker-compose.development.yml file
dev-db-up:
	docker-compose -f docker-compose.development.yml up -d
	
dev-db-down:
	docker-compose -f docker-compose.development.yml down